### ISSUE TITLE
Buoy Telemetry Highlighted Metrics Card

### ISSUE THREAD

**Issue by mcmcgrath13** [ridatadiscoverycenter/buoy-viewer#14]
Card with a table highlighting a few key metrics from the real time buoys

**Comment by tdivoll** [comment]
To-Do:
* Fix displayed date to update with slider
* Fix units to display correct unit for each variable

![image](https://user-images.githubusercontent.com/24841909/167716517-e12ea6a2-5903-4efb-9c05-6db1294d1890.png)
