### ISSUE TITLE
Buoy Telemetry Map

### ISSUE THREAD

**Issue by mcmcgrath13** [ridatadiscoverycenter/buoy-viewer#15]
Card with a domoic acid style map.  Maybe show wind speed and water temp on the map? Go back 24 hours on the slider.

**Comment by tdivoll** [comment]
Researching solutions to display the wind direction indicators

**Comment by tdivoll** [comment]
![image](https://user-images.githubusercontent.com/24841909/159768803-b4c17fe2-c5c0-4a68-a635-ad6faae40013.png)
Pasting here, I'm thinking we can map the wind speed directions to saved icon images for each group of speeds (e.g., 0-2, 2<4.99, 5-9.99, etc.) and then rotate for direction using the degrees

**Comment by tdivoll** [comment]
I have a map added, but pre-commit hook fails to push changes. Need to learn more about pinia, axios, and the `buoy-telemetry` store to fix it.
![image](https://user-images.githubusercontent.com/24841909/161616231-e65400d2-df3f-481c-acf7-b7f7bb56a324.png)

**Comment by tdivoll** [comment]
1. water temp markers
2. switch over to highlighted metrics card
3. wind indicators with SVG

**Comment by mirestrepo** [comment]
- [ ] change the slider to 3 days
- [ ] decrease transparency of marker so it doesn't occlude bouy
- [ ] try if adding the temperature as number inside the circle, adds a valuable perspective

**Comment by tdivoll** [comment]
It was too busy with adding values inside chlorophyll markers on top of buoy icons and wind indicators. Will add a colorscale legend instead.
