### ISSUE TITLE
Clarify RI Data Source

### ISSUE THREAD

**Issue by mcmcgrath13** [ridatadiscoverycenter/buoy-viewer#16]
In the Available data box, clarify the source of the data:

From RIDEM:
> I am wondering if some updates can be made to the website to clearly state the data sources.  For example, the RI buoy.  In the data available from the historical buoy data, could you mention in the Available Data box that the data is from NBFSMN with RIDEM-OWR as lead agency. Agencies involved in collection and maintenance of the data are:RIDEM-OWR, URI/GSO MERL, NBC, NBNERR, and MassDEP.  In addition, label the RI buoy (NBFSMN) and MA buoy (MassDEP/NBFSMN).

**Comment by tdivoll** [comment]
Let me know if we should define all the agency acronyms

**Comment by mcmcgrath13** [comment]
Want to start the glossary page with those in it?

**Comment by mcmcgrath13** [comment]
or we could use `<abbr>` tags

**Comment by tdivoll** [comment]
WIP: add external links to the acronyms
