### ISSUE TITLE
Simplify interpolation loop

### ISSUE THREAD

**Issue by tdivoll** [ridatadiscoverycenter/buoy-viewer#48]
I think this entire for loop can be simplified though let me know if i'm misunderstanding!. Right now, it looks like you're doing the following:

1. Iterating through the list to get a sample (`foundSample`)
2. Then for each sample
    - finding the `nextSample`
    - reversing the list
    - Getting the `prevSample`
    - Interpolating between previous and next. 

which is a lot of going through the same array. I think we can go through the array in fewer steps.! Let me know what you think? We can go through this together too! 

Instead, I think we can do something like the following. ⚠️ This code wasn't tested... i just wrote code.
1. Get all of the foundSamples using `filter`

```js
// foundSamples is now a array of all the foundSamples
      const foundSamples = samples.filter((sample) => {
        return (
          sample.date.valueOf() === selectedDate.value.valueOf() &&
          sample.variable === variable &&
          sample.station_name === coordinate.station_name &&
          sample.value !== null
        );
      });
```
2. Interpolate between each sample. 
```js
const newSamples = foundSamples.reduce((res, foundSample, index, array) => {
    if (index > 0 && index < array.length - 1) {
        const prevSample = array[index - 1];
        const nextSample = array[index + 1];

        const interpolator = scaleLinear(
        [prevSample.date.valueOf(), nextSample.date.valueOf()],
        [prevSample.value, nextSample.value]
        );

        const newValue = interpolator(selectedDate.value.valueOf());
        const newSample = {
        ...nextSample,
        date: selectedDate.value,
        value: newValue,
        };

        res.push(newSample);
    }
    return res;

}, []);
```

_Originally posted by @eldu in https://github.com/ridatadiscoverycenter/buoy-viewer/pull/8#discussion_r883890570_

**Comment by eldu** [comment]
Tim and I talked this through. I didn't realize the implications of missing data. If there is a found sample, we exit early and otherwise we go looking for the previous and next sample. Since we're also just searching for these samples as the user selects a date rather than for 15-min time stamps I think what we currently have for finding the sample values is good enough!
